### ISSUE TITLE
Loader cache must be cleared/recreated on every request

### ISSUE THREAD

**Issue by steveluscher** [buffalojoec/solana-graphql#19]
Imagine you want to watch an account's balance increase over time. Right now, running this query over and over will always return you the same balance, because we don't clear the loaders.

https://graphql.solana.com/#q:0:2:I4VwpgTgngBA4mALgNQPaLAQQMbdSAO0QCEBDAG1IOzBgG8AoGGU3fIgClIBNuIwAzgIBcMAEQAmOAFUCAMwAeALVIA3ANKoACnIDKATgEBmZLoCiAK1IB1ACIAvYkdUA5OQFYASqgvSAFgAOEADCugCMELoKYgCU9EzMMJQAtgGoEIgCCQC+DNlAA

Loaders are only intended to cache inside a _single_ query's request, not between queries.

**Comment by buffalojoec** [comment]
Ha! I just sniffed this out last night, but wanted to circle back to it. Thanks! I'll add to my list.

I was considering the actual resolver's cache, though, which I *thought* was doing what you're describing here, but maybe not (?). There is another cache in the playground, though.
